language: generic 

sudo: required
services:
  - docker


before_install:
  - docker build -t vikas/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true vikas/docker-react npm run test

deploy:
  providers: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-099878648584"
  bucket_path: "docker-react1"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
          secure: "$AWS_SECRET_KEY"     
