language: generic 

sudo: required
services:
  - docker


before_install:
  - docker build -t vikas/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true vikas/docker-react npm run test
